version: "3.3"
services:
    dbs-python-example:
        build: .
        ports:
            - 8000:8000
        environment:
            - DATABASE_HOST=host.docker.internal
            - DATABASE_PORT=5432
            - DATABASE_NAME=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=root
